services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    restart: always
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - media_data:/app/media
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URI=mongodb://mongo:27017/payload-template-ecommerce
    env_file:
      - .env.production
    networks:
      - internal_net

  mongo:
    image: mongo:7-jammy
    restart: always
    command:
      - --storageEngine=wiredTiger
    volumes:
      - mongo_data:/data/db
    networks:
      - internal_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongo_data:
  media_data:

networks:
  internal_net:
    driver: bridge
