version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: t-shop-pod:staging
    restart: always
    ports:
      - '3002:3000'
    environment:
      - PAYLOAD_PUBLIC_SERVER_URL=http://localhost:3002
      - NEXT_PUBLIC_SERVER_URL=http://localhost:3002
      - INTERNAL_SERVER_URL=http://127.0.0.1:3000
    env_file:
      - .env.staging
    volumes:
      - media_data:/app/media
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_DATABASE: payload-template-ecommerce
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  media_data:
